In [114]:
import numpy as np

In [115]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1, 7]])

In [116]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [117]:
mean_a = np.mean(a, axis=0)

In [154]:
mean_a

array([2. , 8.4])

In [120]:
a_centered = np.subtract(a, mean_a)




In [144]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [149]:
a_centered = a_centered.transpose()

In [150]:
a_centered[0], a_centered[1]

(array([-1.,  0.,  1.,  1., -1.]), array([-2.4, -0.4,  2.6,  1.6, -1.4]))

In [151]:
a_centered_sp = np.dot(a_centered[0], a_centered[1])

In [152]:
a_centered_sp

8.0

In [153]:
a_centered_sp / (len(a)- 1)

2.0

In [155]:
a = a.transpose()

In [156]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [157]:
np.cov(a)

array([[1. , 2. ],
       [2. , 4.3]])